apiVersion: v2
name: edgen
description: CUDA-first Helm chart for Edgen OpenAI-compatible local AI server with model preloading
home: https://github.com/tensorlabresearch/helm-edgen
type: application
version: 0.1.4
appVersion: "v0.1.11"
keywords:
  - edgen
  - openai
  - stt
  - llm
  - cuda
sources:
  - https://github.com/edgenai/edgen
  - https://github.com/tensorlabresearch/helm-edgen
maintainers:
  - name: tensorlabresearch
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/helm/icon/color/helm-icon-color.png
