apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edgen-oci
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: edgen
  source:
    repoURL: ghcr.io/tensorlabresearch/charts
    chart: edgen
    targetRevision: 0.1.4
    helm:
      values: |
        gpu:
          enabled: true
          count: 1
          resourceKey: nvidia.com/gpu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
